server:
  port: 8090

spring:
  application:
    name: myapp
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres_db
    username: postgres_user
    password: postgres_password
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always

kafka:
  topics:
    users: users
    items: items
  back-off:
    interval: 5000
    attempts: 3
  listener:
    concurrency: 3
  connection:
    bootstrap-servers: localhost:29092
    consumer:
      groupId: consumer-id
      clientId: consumer-client-di
    producer:
      clientId: producer-client-id
    security:
      protocol: PLAINTEXT
    ssl:
      trust-store-location: ""
      trust-store-type: ""
      trust-store-password: ""
      key-store-location: ""
      key-store-type: ""
      key-store-password: ""
      key-password: ""

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

logging:
  level:
    ru.myapp: info
    root: warn
    org.springframework.web: debug

feign:
  client:
    name: todos-client
    url: https://jsonplaceholder.typicode.com

management:
  endpoints:
    web:
      exposure:
        include: prometheus,env,health,info,caches,beans,activity,scheduledtasks,conditions,env,shutdown,threaddump,metrics,loggers,heapdump,refresh

activity:
  enabled: ${ACTIVITY_ENABLED:true}
