server:
  port: 8080

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  application:
    name: myapp

kafka:
  topics:
    users: users
    items: items
  back-off:
    interval: 5000
    attempts: 3
  listener:
    concurrency: 3
  connection:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      groupId: consumer-id
    producer:
      groupId: producer-id
    security:
      protocol: PLAINTEXT
    ssl:
      trust-store-location: ""
      trust-store-type: ""
      trust-store-password: ""
      key-store-location: ""
      key-store-type: ""
      key-store-password: ""
      key-password: ""


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

logging:
  level:
    ru.myapp: info
    root: warn
    org.springframework.web: debug

feign:
  client:
    name: todos-client
    url: https://jsonplaceholder.typicode.com
