apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: myapp-label
  template:
    metadata:
      labels:
        component: myapp-label
    spec:
      containers:
        - name: myapp-name
          image: sucheit/myapp
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service
            - name: KAFKA_HOST
              value: kafka-service
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: myapp-label
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP