drop table if exists paid_groups cascade;
drop table if exists user_groups cascade;
drop table if exists passports cascade;
drop table if exists users cascade;
drop table if exists groups cascade;
drop table if exists items cascade;

create table if not exists groups
(
    id          integer primary key generated BY DEFAULT as identity,
    name        varchar(100) not null,
    description varchar(255) not null
);

create table if not exists users
(
    id         integer primary key generated by default as identity,
    first_name varchar(50) not null,
    last_name  varchar(50) not null
);

create table if not exists passports
(
    user_id       integer    not null,
    serial_number varchar(5) not null,
    constraint fk_user_id foreign key (user_id) references users (id) on delete cascade on update restrict
);

create table if not exists user_groups
(
    user_id  integer not null,
    group_id integer not null,
    constraint pk primary key (user_id, group_id),
    constraint fk_group_id foreign key (group_id) references groups (id) on delete cascade on update restrict,
    constraint fk_user_id foreign key (user_id) references users (id) on delete cascade on update restrict
);

create table if not exists paid_groups
(
    id   integer primary key,
    cost integer check (10 < cost and cost < 1000) not null,
    constraint fk foreign key (id) references groups (id) on delete cascade on update restrict
);

create table if not exists items
(
    id          integer primary key generated by default as identity,
    name        varchar(255)                 not null,
    description varchar(255)                 not null,
    amount      integer check ( amount > 0 ) not null
);
