create table if not exists items
(
    id          integer primary key generated by default as identity,
    name        varchar(255)                 not null,
    description varchar(255)                 not null,
    amount      integer check ( amount > 0 ) not null
);
