name: Checkstyle Validation

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Укажите вашу версию Java
          distribution: 'temurin'
      - name: Validate with Maven (Checkstyle)
        run: mvn validate